apiVersion: v1
kind: Pod
metadata:
  name: tf-pd
spec:
  restartPolicy: Never
  nodeSelector:
    tf: cnn
  containers:
  - image: 0yukali0/tf:cnn
    name: tf
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /data
      name: tf-volume
  volumes:
  - name: tf-volume
    hostPath:
      # directory location on host
      path: /tf-data
